name: deploy

on:
  push: 
    branches: [ ${{secrets.ACTION_BRANCH}} ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    # Runs a single command using the runners shell
    - name: start
      run : yarn start

    - uses: akhileshns/heroku-deploy@v3.1.6 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_APP_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}} #Must be unique in Heroku
        heroku_email: ${{secrets.HEROKU_ACCOUNT}}
